apiVersion: stacks.kotal.io/v1alpha1
kind: Node
metadata:
  name: stacks-node
spec:
  network: mainnet
  rpcPort: 7777
  resources:
    cpu: "2"
    cpuLimit: "4"
    memory: "2Gi"
    memoryLimit: "4Gi"
    storage: "10Gi"
