
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum-kotal-io-v1alpha1-network
  failurePolicy: Fail
  name: mnetwork.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mnode.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum2-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mnode.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ipfs-kotal-io-v1alpha1-swarm
  failurePolicy: Fail
  name: mswarm.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swarms

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum-kotal-io-v1alpha1-network
  failurePolicy: Fail
  name: vnetwork.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: vnode.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum2-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: vnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: vnode.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipfs-kotal-io-v1alpha1-swarm
  failurePolicy: Fail
  name: vswarm.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swarms
