
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum-kotal-io-v1alpha1-network
  failurePolicy: Fail
  name: mutate-ethereum-v1alpha1-network.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-ethereum-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum2-kotal-io-v1alpha1-beaconnode
  failurePolicy: Fail
  name: mutate-ethereum2-v1alpha1-beaconnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beaconnodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum2-kotal-io-v1alpha1-validator
  failurePolicy: Fail
  name: mutate-ethereum2-v1alpha1-validator.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - validators
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-filecoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ipfs-kotal-io-v1alpha1-swarm
  failurePolicy: Fail
  name: mutate-ipfs-v1alpha1-swarm.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swarms
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum-kotal-io-v1alpha1-network
  failurePolicy: Fail
  name: validate-ethereum-v1alpha1-network.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-ethereum-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum2-kotal-io-v1alpha1-beaconnode
  failurePolicy: Fail
  name: validate-ethereum2-v1alpha1-beaconnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beaconnodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum2-kotal-io-v1alpha1-validator
  failurePolicy: Fail
  name: validate-ethereum2-v1alpha1-validator.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - validators
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-filecoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipfs-kotal-io-v1alpha1-swarm
  failurePolicy: Fail
  name: validate-ipfs-v1alpha1-swarm.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swarms
  sideEffects: None
