# permissions for end users to edit swarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swarm-editor-role
rules:
- apiGroups:
  - ipfs.kotal.io
  resources:
  - swarms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipfs.kotal.io
  resources:
  - swarms/status
  verbs:
  - get
