# permissions for end users to view swarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swarm-viewer-role
rules:
- apiGroups:
  - ipfs.kotal.io
  resources:
  - swarms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipfs.kotal.io
  resources:
  - swarms/status
  verbs:
  - get
