apiVersion: ethereum2.kotal.io/v1alpha1
kind: Validator
metadata:
  name: teku-validator
spec:
  client: teku
  network: mainnet
  beaconEndpoint: http://10.96.130.88:9999
  graffiti: Validated by Kotal
  # my-vaidator secret must exist before deploying the validator
  # my-validator secret must has [keystore] and [password] keys
  # key is the keystore file
  # password is the password file
  keystores:
    - secretName: my-validator