apiVersion: ethereum2.kotal.io/v1alpha1
kind: BeaconNode
metadata:
  name: prysm-beacon-node
spec:
  network: pyrmont
  client: prysm
  rpc: true
  rpcPort: 8888
  grpc: true
  grpcPort: 9999
  eth1Endpoints:
    - http://localhost:8545
    - http://localhost:8546
  resources:
    # these resources are only for testing
    # change resources depending on your use case
    cpu: "1"
    memory: "1Gi"
