apiVersion: ethereum2.kotal.io/v1alpha1
kind: BeaconNode
metadata:
  name: teku-beacon-node
spec:
  network: mainnet
  client: teku
  rest: true
  restPort: 8888
  eth1Endpoints:
    - http://localhost:8545
    - http://localhost:8546
