apiVersion: ethereum2.kotal.io/v1alpha1
kind: Validator
metadata:
  name: prysm-validator
spec:
  client: prysm
  network: mainnet
  beaconEndpoint: http://10.96.130.88:9999
  graffiti: Validated by Kotal

