apiVersion: ethereum2.kotal.io/v1alpha1
kind: BeaconNode
metadata:
  name: prysm-beacon-node
spec:
  join: pyrmont
  client: prysm
  rpc: true
  rpcPort: 8888
  grpc: true
  grpcPort: 9999
  eth1Endpoints: 
    - http://localhost:8545
    - http://localhost:8546
