apiVersion: ethereum2.kotal.io/v1alpha1
kind: BeaconNode
metadata:
  name: nimbus-beacon-node
spec:
  network: pyrmont
  client: nimbus
  rpc: true
  rpcPort: 8888
  eth1Endpoints:
    - http://localhost:8545
