apiVersion: ethereum2.kotal.io/v1alpha1
kind: Validator
metadata:
  name: nimbus-validator
spec:
  client: nimbus
  network: mainnet
  beaconEndpoint: http://10.96.130.88:9999
  graffiti: Validated by Kotal
  keystores:
    - secretName: my-validator

