apiVersion: ethereum.kotal.io/v1alpha1
kind: Network
metadata:
  name: ibft2-network-no-genesis-ibft2
spec:
  consensus: ibft2
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    ibft2:
      validators:
        - "0x427e2c7cecd72bc4cdd4f7ebb8bb6e49789c8044"
        - "0xd2c21213027cbf4d46c16b55fa98e5252b048706"
        - "0x8e1f6c7c76a1d7f74eda342d330ca9749f31cc2b"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### network nodes spec ###########
  nodes:
    - name: node-1
      rpc: true
      nodekey: "0x608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e"
      rpcPort: 8599
      rpcHost: 0.0.0.0
      corsDomains:
        - all
      hosts:
        - all
      rpcAPI:
        - web3
        - net
        - eth
        - ibft
    - name: node-2
      nodekey: "0xb4c6097d5db1fabb037f71e21229d59a0161e0f8d407d787f3ba92f25bd39eaf"
    - name: node-3
      nodekey: "0xcb9db0b0927a3095eb2dcd82666c6a602e03379e09ac115260091cb68ca5b075"
    - name: node-4
    - name: node-5

