apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: poa-besu-node
spec:
  consensus: poa
  id: 20189
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    clique:
      blockPeriod: 15
      epochLength: 100
      signers:
        - "0xd2c21213027cbf4d46c16b55fa98e5252b048706"
        - "0x2b3430337f12Ce89EaBC7b0d865F4253c7744c0d"
    forks:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
      berlin: 0
    coinbase: "0x071E2c1067c24607fF00cEEBbe83a38063BDEDd8"
    difficulty: "0xfff"
    gasLimit: "0x47b760"
    nonce: "0x0"
    timestamp: "0x0"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### network nodes spec ###########
  client: besu
  rpc: true
  # kubectl create secret generic nodekey --from-literal=key=608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
  nodekeySecretName: nodekey
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
    - clique
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
