apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: pow-besu-node
spec:
  consensus: pow
  id: 11
  ########### Genesis block spec ###########
  genesis:
    chainId: 9999
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: besu
  miner: true
  coinbase: "0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c"
  bootnode: true
  # kubectl create secret generic node1key --from-literal=key=608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
  nodekeySecretName: node1key
  rpc: true
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
