apiVersion: ethereum.kotal.io/v1alpha1
kind: Network
metadata:
  name: network-sample
spec:
  join: mainnet
  nodes:
    - name: node-1
      client: besu
      bootnode: true
      nodekey: "0x5df5eff7ef9e4e82739b68a34c6b23608d79ee8daf3b598a01ffb0dd7aa3a2fd"
      rpc: true
      rpcPort: 8599
      corsDomains:
        - example.kotal.io
      rpcAPI:
        - web3
        - net
        - eth
      graphql: true
      graphqlPort: 8777
    - name: node-2
      client: geth
    - name: node-3
      client: parity
