apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: pow-parity-node
spec:
  consensus: pow
  id: 20189
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    forks:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
    coinbase: "0x071e2c1067c24607ff00ceebbe83a38063bdedd8"
    difficulty: "0x1"
    gasLimit: "0x47b760"
    nonce: "0x0"
    timestamp: "0x5f69fcd9"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### network nodes spec ###########
  client: parity
  rpc: true
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
