# 🔥 Fetch devnet genesis block
# $ wget https://devnet.aptoslabs.com/genesis.blob
# 🔥 Create k8s configmap from genesis blob file
# $ kubectl create configmap devnet-genesis --from-file genesis.blob
---
# WARNING: DON'T use the following secret in production
# https://aptos.dev/tutorials/full-node/network-identity-fullnode/
apiVersion: v1
kind: Secret
metadata:
  name: node-private-key
stringData:
  key: 755EFCB7A02248562228CC7AF80FC667B7B9360541B165A1A2B97742AAC30AB7
---
apiVersion: aptos.kotal.io/v1alpha1
kind: Node
metadata:
  name: aptos-devnet-node
spec:
  network: devnet
  waypoint: "0:3d27d90783d6f9990365a3d2420127b49455e6c9e8a7cf0b82b87767a2c7dd27"
  genesisConfigmapName: devnet-genesis
  nodePrivateKeySecretName: node-private-key
