# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: kotal-json-rpc-user-password
stringData:
  password: secret
---
# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: dummy-json-rpc-user-password
stringData:
  password: s3cr3t
---
apiVersion: bitcoin.kotal.io/v1alpha1
kind: Node
metadata:
  name: bitcoin-node
spec:
  network: mainnet
  wallet: false
  rpc: true
  rpcPort: 7777
  rpcHost: 0.0.0.0
  rpcUsers:
    - username: kotal
      passwordSecretName: kotal-json-rpc-user-password
    - username: dummy
      passwordSecretName: dummy-json-rpc-user-password
