apiVersion: chainlink.kotal.io/v1alpha1
kind: Node
metadata:
  name: node-sample
spec:
  ethereumChainId: 1
  ethereumWsEndpoint: "ws://my-eth-node:8546"
  linkContractAddress: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
